In [1]:
import pandas as pd
import numpy as np
from google.cloud import bigquery
import pickle
from datetime import date, datetime, timezone
from pathlib import Path

import warnings
warnings.filterwarnings("ignore")

In [2]:
def run_query(query): 
    # Set up the BigQuery client
    project_id = 'som-nero-phi-sywang-starr'
    client = bigquery.Client(project=project_id)

    # Execute the query
    df = client.query(query, project=project_id).to_dataframe()

    return df

In [3]:
DATA_DIR = Path("processed_data_two_codes")

## Load Initial Cohort

In [4]:
cohort = pd.read_csv(DATA_DIR / "cohort.csv", dtype={'MRN': 'string'})

In [5]:
cohort.head()

         MRN  outcome   diag_date
0  20278404         1  2008-01-17
1  27652908         1  2014-04-03
2  17562414         1  2011-04-20
3  18737130         1  2010-04-13
4  00768895         1  2012-04-10

In [6]:
print(f'There is a total of {len(cohort)} patients in this cohort.')

There is a total of 20636 patients in this cohort.

## Load Measurement Data

In [7]:
query = """
SELECT 
    co.measurement_id,
    co.person_id,
    co.measurement_concept_id,
    co.measurement_datetime,
    co.value_as_number,
    mc.*
FROM `som-nero-phi-sywang-starr.gps_stanford_clinic.measurement` AS co
LEFT JOIN `som-nero-phi-sywang-starr.gps_stanford_clinic.mrn_crosswalk` AS mc
ON co.person_id = mc.person_id;

"""

lab_dat = run_query(query)
lab_dat = lab_dat.drop(columns = ['person_id','person_id_1', 'source_dob'], axis = 1, inplace = False)
print(f"# of rows: {len(lab_dat)}")
print(f"# of unique pats: {len(lab_dat['MRN'].unique())}")

# of rows: 144790523
# of unique pats: 22656

In [8]:
lab_dat.head()

,measurement_id,measurement_concept_id,measurement_datetime,value_as_number,MRN
0,40505360,4036357,2010-02-23 07:30:00,4.000,17274309
1,1507614247,3019762,2023-06-19 13:58:00,1.600,60656055
2,1933226923,3009201,2018-03-30 16:13:00,1.200,47684196
3,2434858800,3009201,2003-10-13 10:31:00,0.491,15201395
4,1284583375,3009201,2007-12-18 09:49:00,1.660,11528262

In [9]:
x = lab_dat.merge(cohort, on='MRN', how='left')

In [10]:
filtered_x = x[(x.measurement_datetime <= x.diag_date) | x.diag_date.isna()]
filtered_x.drop(columns = ['measurement_id', 'outcome', 'diag_date'], axis = 1, inplace = True)

In [11]:
filtered_x.head()

   measurement_concept_id measurement_datetime  value_as_number        MRN
0                 4036357  2010-02-23 07:30:00            4.000  17274309
1                 3019762  2023-06-19 13:58:00            1.600  60656055
2                 3009201  2018-03-30 16:13:00            1.200  47684196
3                 3009201  2003-10-13 10:31:00            0.491  15201395
4                 3009201  2007-12-18 09:49:00            1.660  11528262

In [12]:
lab_data = filtered_x

## Extract Features

### Helper Functions

In [13]:
def get_unique_data(concept_id, col_name, keep_date = False, data_col_name = None):
    df = lab_data[lab_data.measurement_concept_id == concept_id][['MRN', 'value_as_number',
                                                                  'measurement_datetime']]
    df.rename(columns={'value_as_number': col_name}, inplace=True)
    if keep_date:
        df.rename(columns={'measurement_datetime': data_col_name}, inplace=True)
        
    df = df[df[col_name].notna()]

    unique_pats_before = len(df['MRN'].unique())
    
    if keep_date:
        df = df.sort_values(data_col_name).groupby('MRN').last().reset_index()
    else:
        df = df.sort_values('measurement_datetime').groupby('MRN').last().reset_index()
    
    unique_pats_after = len(df['MRN'].unique())
    assert unique_pats_before == unique_pats_after
    
    if not keep_date:
        df.drop(['measurement_datetime'], axis = 1, inplace = True)
    print(f'Unique Pats: {unique_pats_after}')
    return df

In [14]:
def combine_cols(df1, df2, df1_col, df2_col, df1_date_col, df2_date_col, col_name,
                 keep_date = False, date_col = None):
    df1[df1_date_col] = pd.to_datetime(df1[df1_date_col])

    if df1[df1_date_col].dt.tz is None:  # If naive, localize
        df1[df1_date_col] = df1[df1_date_col].dt.tz_localize('UTC')
    else:  # If already aware, convert to UTC
        df1[df1_date_col] = df1[df1_date_col].dt.tz_convert('UTC')

    df2[df2_date_col] = pd.to_datetime(df2[df2_date_col])

    if df2[df2_date_col].dt.tz is None:
        df2[df2_date_col] = df2[df2_date_col].dt.tz_localize('UTC')
    else:
        df2[df2_date_col] = df2[df2_date_col].dt.tz_convert('UTC')

    
    combined_df = pd.merge(df1, df2, how='outer', on = 'MRN')
    dt = (datetime.now(timezone.utc))
    
    combined_df[df1_date_col] = combined_df[df1_date_col].fillna(dt.replace(year=dt.year-200))
    combined_df[df2_date_col] = combined_df[df2_date_col].fillna(dt.replace(year=dt.year-200))
    combined_df[col_name] = np.where(combined_df[df2_date_col] > combined_df[df1_date_col],
                              combined_df[df2_col], combined_df[df1_col])
    
    if keep_date:
        combined_df[date_col] = np.where(combined_df[df2_date_col] > combined_df[df1_date_col],
                          combined_df[df2_date_col], combined_df[df1_date_col])
    
    combined_df.drop([df2_date_col, df1_date_col, df2_col, df1_col],axis = 1, inplace = True)
    
    unique_pats = len(combined_df['MRN'].unique())
    print(f'Unique Pats: {unique_pats}')
    print(combined_df.head())
    
    return combined_df

### BMI, BP, Heart Rate

In [15]:
# bmi
bmi = get_unique_data(3038553, 'bmi', keep_date = False, data_col_name = None)
bmi.head()

Unique Pats: 21822

         MRN    bmi
0  00002048   26.11
1  00006825   25.17
2  00010603   35.47
3  00013474   31.46
4  00018895   18.36

In [16]:
# diastolic bp
dbp = get_unique_data(3012888, 'dbp', keep_date = False, data_col_name = None)
dbp.head()

Unique Pats: 21888

         MRN   dbp
0  00002048   71.0
1  00006825   63.0
2  00010603   71.0
3  00013474   63.0
4  00018895   61.0

In [17]:
# systolic bp
sbp = get_unique_data(3004249, 'sbp', keep_date = False, data_col_name = None)
sbp.head()

Unique Pats: 21888

         MRN    sbp
0  00002048   148.0
1  00006825   155.0
2  00010603   117.0
3  00013474   130.0
4  00018895   169.0

In [18]:
# heart rate
heart_rate = get_unique_data(3027018, 'heart_rate', keep_date = False, data_col_name = None)
heart_rate.head()

Unique Pats: 21870

         MRN  heart_rate
0  00002048         74.0
1  00006825         72.0
2  00010603         95.0
3  00013474         78.0
4  00018895         58.0

In [19]:
lab_df = pd.merge(sbp, dbp, how='outer', on = 'MRN')
lab_df = pd.merge(lab_df, heart_rate, how='outer', on = 'MRN')
lab_df = pd.merge(lab_df, bmi, how='outer', on = 'MRN')

unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22133

         MRN    sbp   dbp  heart_rate    bmi
0  00002048   148.0  71.0        74.0  26.11
1  00006825   155.0  63.0        72.0  25.17
2  00010603   117.0  71.0        95.0  35.47
3  00013474   130.0  63.0        78.0  31.46
4  00018895   169.0  61.0        58.0  18.36

### Hemoglobin A1C

In [20]:
a1c = get_unique_data(3004410, 'a1c', keep_date = False, data_col_name = None)
a1c.head()

Unique Pats: 16272

         MRN  a1c
0  00002048   6.4
1  00006825   9.1
2  00010603   5.5
3  00013474   5.2
4  00018895   5.4

In [21]:
lab_df = pd.merge(lab_df, a1c, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22194

         MRN    sbp   dbp  heart_rate    bmi  a1c
0  00002048   148.0  71.0        74.0  26.11  6.4
1  00006825   155.0  63.0        72.0  25.17  9.1
2  00010603   117.0  71.0        95.0  35.47  5.5
3  00013474   130.0  63.0        78.0  31.46  5.2
4  00018895   169.0  61.0        58.0  18.36  5.4

### Thyroid-Stimulating Hormone (TSH)

In [22]:
tsh = get_unique_data(3009201, 'tsh', keep_date = False, data_col_name = None)
tsh.head()

Unique Pats: 17128

         MRN   tsh
0  00002048   3.11
1  00006825   2.58
2  00010603   2.14
3  00013474   2.88
4  00018895   2.66

In [23]:
lab_df = pd.merge(lab_df, tsh, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22256

         MRN    sbp   dbp  heart_rate    bmi  a1c   tsh
0  00002048   148.0  71.0        74.0  26.11  6.4  3.11
1  00006825   155.0  63.0        72.0  25.17  9.1  2.58
2  00010603   117.0  71.0        95.0  35.47  5.5  2.14
3  00013474   130.0  63.0        78.0  31.46  5.2  2.88
4  00018895   169.0  61.0        58.0  18.36  5.4  2.66

### Lipid Panel

In [24]:
# Total Cholestrol
total_chol = get_unique_data(3027114, 'total_chol', keep_date = False, data_col_name = None)
total_chol.head()

Unique Pats: 17438

         MRN  total_chol
0  00002048        152.0
1  00006825        177.0
2  00010603        195.0
3  00013474        190.0
4  00018895        190.0

In [25]:
# (LDL) Cholesterol
ldl_chol = get_unique_data(3028288, 'ldl_chol', keep_date = False, data_col_name = None)
ldl_chol.head()

Unique Pats: 13856

         MRN  ldl_chol
0  00002048       77.0
1  00006825      113.0
2  00010603      150.0
3  00013474      104.0
4  00018895       96.0

In [26]:
# (HDL) Cholesterol
hdl_chol = get_unique_data(3007070, 'hdl_chol', keep_date = False, data_col_name = None)
hdl_chol.head()

Unique Pats: 17388

         MRN  hdl_chol
0  00002048       48.0
1  00006825       48.0
2  00010603       60.0
3  00013474       67.0
4  00018895       82.0

In [27]:
# (Non-HDL) Cholesterol
nonhdl_chol = get_unique_data(3044491, 'nonhdl_chol', keep_date = False, data_col_name = None)
nonhdl_chol.head()

Unique Pats: 14813

         MRN  nonhdl_chol
0  00002048         104.0
1  00006825         129.0
2  00010603         135.0
3  00013474         123.0
4  00033100         130.0

In [28]:
# Triglyceride
triglyceride = get_unique_data(3022192, 'triglyceride', keep_date = False, data_col_name = None)
triglyceride.head()

Unique Pats: 645

         MRN  triglyceride
0  01071976           91.0
1  01248665          109.0
2  01323211           48.0
3  01375872           56.0
4  02290385           49.0

In [29]:
lipid = pd.merge(total_chol, ldl_chol, how='outer', on = 'MRN')
lipid = pd.merge(lipid, hdl_chol, how='outer', on = 'MRN')
lipid = pd.merge(lipid, nonhdl_chol, how='outer', on = 'MRN')
lipid = pd.merge(lipid, triglyceride, how='outer', on = 'MRN')
print(f'Unique Pats: {unique_pats}')
lipid.head()

Unique Pats: 22256

         MRN  total_chol  ldl_chol  hdl_chol  nonhdl_chol  triglyceride
0  00002048        152.0      77.0      48.0        104.0           NaN
1  00006825        177.0     113.0      48.0        129.0           NaN
2  00010603        195.0     150.0      60.0        135.0           NaN
3  00013474        190.0     104.0      67.0        123.0           NaN
4  00018895        190.0      96.0      82.0          NaN           NaN

In [30]:
lab_df = pd.merge(lab_df, lipid, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22275

,MRN,sbp,dbp,heart_rate,bmi,a1c,tsh,total_chol,ldl_chol,hdl_chol,nonhdl_chol,triglyceride
0,00002048,148.0,71.0,74.0,26.11,6.4,3.11,152.0,77.0,48.0,104.0,NaN
1,00006825,155.0,63.0,72.0,25.17,9.1,2.58,177.0,113.0,48.0,129.0,NaN
2,00010603,117.0,71.0,95.0,35.47,5.5,2.14,195.0,150.0,60.0,135.0,NaN
3,00013474,130.0,63.0,78.0,31.46,5.2,2.88,190.0,104.0,67.0,123.0,NaN
4,00018895,169.0,61.0,58.0,18.36,5.4,2.66,190.0,96.0,82.0,NaN,NaN

### CBC Panel

In [31]:
# Red Blood Cells
red_blood = get_unique_data(3020416, 'red_blood', keep_date = False, data_col_name = None)
red_blood.head()

Unique Pats: 20450

         MRN  red_blood
0  00002048        3.94
1  00006825        4.23
2  00010603        3.80
3  00013474        4.62
4  00018895        3.25

In [32]:
# White Blood Cells
white_blood = get_unique_data(3000905, 'white_blood', keep_date = False, data_col_name = None)
white_blood.head()

Unique Pats: 17499

         MRN  white_blood
0  00002048           7.7
1  00006825           6.5
2  00010603          14.2
3  00013474           6.9
4  00033100           6.2

In [33]:
# Hemoglobin
hemoglobin = get_unique_data(3000963, 'hemoglobin', keep_date = False, data_col_name = None)
hemoglobin.head()

Unique Pats: 20452

         MRN  hemoglobin
0  00002048         12.1
1  00006825         13.8
2  00010603         12.3
3  00013474         13.7
4  00018895         11.3

In [34]:
# Hematocrit
hematocrit = get_unique_data(3023314, 'hematocrit', keep_date = False, data_col_name = None)
hematocrit.head()

Unique Pats: 20470

         MRN  hematocrit
0  00002048         36.7
1  00006825         42.9
2  00010603         39.0
3  00013474         43.7
4  00018895         33.2

In [35]:
# Platelets
platelets = get_unique_data(3024929, 'platelets', keep_date = False, data_col_name = None)
platelets.head()

Unique Pats: 20455

         MRN  platelets
0  00002048       187.0
1  00006825       177.0
2  00010603       241.0
3  00013474       291.0
4  00018895       162.0

In [36]:
cbc = pd.merge(white_blood, red_blood, how='outer', on = 'MRN')
cbc = pd.merge(cbc, hemoglobin, how='outer', on = 'MRN')
cbc = pd.merge(cbc, hematocrit, how='outer', on = 'MRN')
cbc = pd.merge(cbc, platelets, how='outer', on = 'MRN')
unique_pats = len(cbc['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
cbc.head()

Unique Pats: 20492

         MRN  white_blood  red_blood  hemoglobin  hematocrit  platelets
0  00002048           7.7       3.94        12.1        36.7      187.0
1  00006825           6.5       4.23        13.8        42.9      177.0
2  00010603          14.2       3.80        12.3        39.0      241.0
3  00013474           6.9       4.62        13.7        43.7      291.0
4  00018895           NaN       3.25        11.3        33.2      162.0

In [37]:
lab_df = pd.merge(lab_df, cbc, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22313

,MRN,sbp,dbp,heart_rate,bmi,a1c,tsh,total_chol,ldl_chol,hdl_chol,nonhdl_chol,triglyceride,white_blood,red_blood,hemoglobin,hematocrit,platelets
0,00002048,148.0,71.0,74.0,26.11,6.4,3.11,152.0,77.0,48.0,104.0,NaN,7.7,3.94,12.1,36.7,187.0
1,00006825,155.0,63.0,72.0,25.17,9.1,2.58,177.0,113.0,48.0,129.0,NaN,6.5,4.23,13.8,42.9,177.0
2,00010603,117.0,71.0,95.0,35.47,5.5,2.14,195.0,150.0,60.0,135.0,NaN,14.2,3.80,12.3,39.0,241.0
3,00013474,130.0,63.0,78.0,31.46,5.2,2.88,190.0,104.0,67.0,123.0,NaN,6.9,4.62,13.7,43.7,291.0
4,00018895,169.0,61.0,58.0,18.36,5.4,2.66,190.0,96.0,82.0,NaN,NaN,NaN,3.25,11.3,33.2,162.0

### Comprehensive Metabolic Panel (CMP)

In [38]:
# Sodium
sodium_1 = get_unique_data(3000285, 'sodium_1', keep_date = True, data_col_name = 'measurement_datetime_1')
sodium_2 = get_unique_data(3019550, 'sodium_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 6269
Unique Pats: 20533

In [39]:
sodium = combine_cols(sodium_1, sodium_2, 'sodium_1', 'sodium_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'sodium', keep_date = False)

Unique Pats: 20559
         MRN  sodium
0  00002048    142.0
1  00006825    141.0
2  00010603    140.0
3  00013474    138.0
4  00018895    131.0

In [40]:
# Potassium
potassium_1 = get_unique_data(3005456, 'potassium_1', keep_date = True, data_col_name = 'measurement_datetime_1')
potassium_2 = get_unique_data(3023103, 'potassium_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 3364
Unique Pats: 20539

In [41]:
potassium = combine_cols(potassium_1, potassium_2, 'potassium_1', 'potassium_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'potassium', keep_date = False)

Unique Pats: 20554
         MRN  potassium
0  00002048         5.0
1  00006825         3.9
2  00010603         4.2
3  00013474         4.6
4  00018895         4.8

In [42]:
# Chloride
chloride_1 = get_unique_data(3018572, 'chloride_1', keep_date = True, data_col_name = 'measurement_datetime_1')
chloride_2 = get_unique_data(3014576, 'chloride_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 61
Unique Pats: 20532

In [43]:
chloride = combine_cols(chloride_1, chloride_2, 'chloride_1', 'chloride_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'chloride', keep_date = False)

Unique Pats: 20532
         MRN  chloride
0  00002048      106.0
1  00006825      105.0
2  00010603      102.0
3  00013474      101.0
4  00018895       99.0

In [44]:
# Cardon Dioxide
co2_1 = get_unique_data(3014094, 'co2_1', keep_date = True, data_col_name = 'measurement_datetime_1')
co2_2 = get_unique_data(3015632, 'co2_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 0
Unique Pats: 20528

In [45]:
co2 = combine_cols(co2_1, co2_2, 'co2_1', 'co2_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'co2', keep_date = False)

Unique Pats: 20528
         MRN   co2
0  00002048   28.0
1  00006825   27.0
2  00010603   28.0
3  00013474   30.0
4  00018895   29.0

In [46]:
# Albumin
albumin = get_unique_data(3024561, 'albumin', keep_date = False)
albumin.head()

Unique Pats: 20082

         MRN  albumin
0  00002048       4.3
1  00006825       3.5
2  00010603       2.9
3  00013474       4.9
4  00018895       4.0

In [47]:
# Alkaline Phosphatase
alk_phos_1 = get_unique_data(3001110, 'alk_phos_1', keep_date = True, data_col_name = 'measurement_datetime_1')
alk_phos_2 = get_unique_data(3035995, 'alk_phos_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 0
Unique Pats: 20133

In [48]:
alk_phos = combine_cols(alk_phos_1, alk_phos_2, 'alk_phos_1', 'alk_phos_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'alk_phos', keep_date = False)

Unique Pats: 20133
         MRN  alk_phos
0  00002048       73.0
1  00006825      130.0
2  00010603       54.0
3  00013474       86.0
4  00018895       71.0

In [49]:
# Bilirubin
bilirubin_1 = get_unique_data(3028833, 'bilirubin_1', keep_date = True, data_col_name = 'measurement_datetime_1')
bilirubin_2 = get_unique_data(3024128, 'bilirubin_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 0
Unique Pats: 20049

In [50]:
bilirubin = combine_cols(bilirubin_1, bilirubin_2, 'bilirubin_1', 'bilirubin_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'bilirubin', keep_date = False)

Unique Pats: 20049
         MRN  bilirubin
0  00002048         0.4
1  00006825         0.5
2  00010603         0.3
3  00013474         0.5
4  00018895         1.1

In [51]:
# Aspartate Transaminase
aspartate_trans_1a = get_unique_data(3013721, 'aspartate_trans_1a', keep_date = True,
                                     data_col_name = 'measurement_datetime_1a')
aspartate_trans_1b = get_unique_data(36305398, 'aspartate_trans_1b', keep_date = True,
                                     data_col_name = 'measurement_datetime_2a')
aspartate_trans_1 = combine_cols(aspartate_trans_1a, aspartate_trans_1b, 'aspartate_trans_1a', 'aspartate_trans_1b', 
             'measurement_datetime_1a', 'measurement_datetime_2a', 'aspartate_trans_1', keep_date = True,
                                 date_col = 'measurement_datetime_1')

Unique Pats: 20111
Unique Pats: 0
Unique Pats: 20111
         MRN  aspartate_trans_1    measurement_datetime_1
0  00002048                24.0 2024-12-18 11:26:00+00:00
1  00006825                30.0 2020-06-04 14:49:00+00:00
2  00010603                28.0 2020-01-27 06:17:00+00:00
3  00013474                26.0 2023-08-31 11:08:00+00:00
4  00018895                36.0 2014-01-24 08:00:00+00:00

In [52]:
aspartate_trans_2 = get_unique_data(3037081, 'aspartate_trans_2',
                                    keep_date = True, data_col_name = 'measurement_datetime_2')
aspartate_trans = combine_cols(aspartate_trans_1, aspartate_trans_2, 'aspartate_trans_1', 'aspartate_trans_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'aspartate_trans', keep_date = False)

Unique Pats: 0
Unique Pats: 20111
         MRN  aspartate_trans
0  00002048              24.0
1  00006825              30.0
2  00010603              28.0
3  00013474              26.0
4  00018895              36.0

In [53]:
# Alanine Transaminase
alaine_trans_1a = get_unique_data(46235106, 'alaine_trans_1a', keep_date = True,
                                     data_col_name = 'measurement_datetime_1a')
alaine_trans_1b = get_unique_data(3006923, 'alaine_trans_1b', keep_date = True,
                                     data_col_name = 'measurement_datetime_1b')

alaine_trans_1 = combine_cols(alaine_trans_1a, alaine_trans_1b, 'alaine_trans_1a', 'alaine_trans_1b', 
             'measurement_datetime_1a', 'measurement_datetime_1b', 'alaine_trans_1', keep_date = True,
                                 date_col = 'measurement_datetime_1')

Unique Pats: 0
Unique Pats: 20124
Unique Pats: 20124
         MRN  alaine_trans_1    measurement_datetime_1
0  00002048             22.0 2024-12-18 11:26:00+00:00
1  00006825             34.0 2020-06-04 14:49:00+00:00
2  00010603             13.0 2020-01-27 06:17:00+00:00
3  00013474             19.0 2023-08-31 11:08:00+00:00
4  00018895             34.0 2014-01-24 08:00:00+00:00

In [54]:
alaine_trans_2a = get_unique_data(3027388, 'alaine_trans_2a', keep_date = True,
                                     data_col_name = 'measurement_datetime_2a')
alaine_trans_2b = get_unique_data(3005755, 'alaine_trans_2b', keep_date = True,
                                     data_col_name = 'measurement_datetime_2b')

alaine_trans_2 = combine_cols(alaine_trans_2a, alaine_trans_2b, 'alaine_trans_2a', 'alaine_trans_2b', 
             'measurement_datetime_2a', 'measurement_datetime_2b', 'alaine_trans_2', keep_date = True,
                                 date_col = 'measurement_datetime_2')

Unique Pats: 0
Unique Pats: 221
Unique Pats: 221
         MRN  alaine_trans_2    measurement_datetime_2
0  00221929              8.0 2018-04-06 11:43:00+00:00
1  00933622             17.0 2021-12-17 10:45:00+00:00
2  02097509             29.0 2023-10-18 18:04:00+00:00
3  02996361             42.0 2024-10-04 16:01:00+00:00
4  03153665             17.0 2024-04-25 15:07:00+00:00

In [55]:
alaine_trans = combine_cols(alaine_trans_1, alaine_trans_2, 'alaine_trans_1', 'alaine_trans_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'alaine_trans', keep_date = False)

Unique Pats: 20124
         MRN  alaine_trans
0  00002048           22.0
1  00006825           34.0
2  00010603           13.0
3  00013474           19.0
4  00018895           34.0

In [56]:
# Blood Urea Nitrogen
blood_urea_nit = get_unique_data(3013682, 'blood_urea_nit', keep_date = False)
blood_urea_nit.head()

Unique Pats: 20538

         MRN  blood_urea_nit
0  00002048             31.0
1  00006825             26.0
2  00010603              8.0
3  00013474             18.0
4  00018895             14.0

In [57]:
# Total Protein
protein = get_unique_data(3020630, 'protein', keep_date = False)
protein.head()

Unique Pats: 20031

         MRN  protein
0  00002048       7.3
1  00006825       6.1
2  00010603       6.0
3  00013474       7.5
4  00018895       6.6

In [58]:
# Calcium
calcium = get_unique_data(3006906, 'calcium', keep_date = False)
calcium.head()

Unique Pats: 20525

         MRN  calcium
0  00002048      10.3
1  00006825      10.7
2  00010603       8.7
3  00013474       9.6
4  00018895       9.3

In [59]:
# Creatinine
creatinine = get_unique_data(3016723, 'creatinine', keep_date = False)
creatinine.head()

Unique Pats: 20601

         MRN  creatinine
0  00002048         1.40
1  00006825         0.99
2  00010603         0.51
3  00013474         0.63
4  00018895         0.50

In [60]:
# Glucose
glucose_1 = get_unique_data(3000483, 'glucose_1', keep_date = True, data_col_name = 'measurement_datetime_1')
glucose_2 = get_unique_data(3004501, 'glucose_2', keep_date = True, data_col_name = 'measurement_datetime_2')

Unique Pats: 6650
Unique Pats: 20511

In [61]:
glucose = combine_cols(glucose_1, glucose_2, 'glucose_1', 'glucose_2', 
             'measurement_datetime_1', 'measurement_datetime_2', 'glucose', keep_date = False)

Unique Pats: 20567
         MRN  glucose
0  00002048     110.0
1  00006825     203.0
2  00010603      91.0
3  00013474      90.0
4  00018895      97.0

In [62]:
cmp = pd.merge(sodium, potassium, how='outer', on = 'MRN')
cmp = pd.merge(cmp, chloride, how='outer', on = 'MRN')
cmp = pd.merge(cmp, co2, how='outer', on = 'MRN')
cmp = pd.merge(cmp, albumin, how='outer', on = 'MRN')
cmp = pd.merge(cmp, alk_phos, how='outer', on = 'MRN')

cmp = pd.merge(cmp, bilirubin, how='outer', on = 'MRN')
cmp = pd.merge(cmp, aspartate_trans, how='outer', on = 'MRN')
cmp = pd.merge(cmp, alaine_trans, how='outer', on = 'MRN')

cmp = pd.merge(cmp, blood_urea_nit, how='outer', on = 'MRN')
cmp = pd.merge(cmp, protein, how='outer', on = 'MRN')
cmp = pd.merge(cmp, calcium, how='outer', on = 'MRN')
cmp = pd.merge(cmp, creatinine, how='outer', on = 'MRN')
cmp = pd.merge(cmp, glucose, how='outer', on = 'MRN')

unique_pats = len(cmp['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
cmp.head()

Unique Pats: 20813

,MRN,sodium,potassium,chloride,co2,albumin,alk_phos,bilirubin,aspartate_trans,alaine_trans,blood_urea_nit,protein,calcium,creatinine,glucose
0,00002048,142.0,5.0,106.0,28.0,4.3,73.0,0.4,24.0,22.0,31.0,7.3,10.3,1.40,110.0
1,00006825,141.0,3.9,105.0,27.0,3.5,130.0,0.5,30.0,34.0,26.0,6.1,10.7,0.99,203.0
2,00010603,140.0,4.2,102.0,28.0,2.9,54.0,0.3,28.0,13.0,8.0,6.0,8.7,0.51,91.0
3,00013474,138.0,4.6,101.0,30.0,4.9,86.0,0.5,26.0,19.0,18.0,7.5,9.6,0.63,90.0
4,00018895,131.0,4.8,99.0,29.0,4.0,71.0,1.1,36.0,34.0,14.0,6.6,9.3,0.50,97.0

In [63]:
lab_df = pd.merge(lab_df, cmp, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22323

,MRN,sbp,dbp,heart_rate,bmi,a1c,tsh,total_chol,ldl_chol,hdl_chol,...,albumin,alk_phos,bilirubin,aspartate_trans,alaine_trans,blood_urea_nit,protein,calcium,creatinine,glucose
0,00002048,148.0,71.0,74.0,26.11,6.4,3.11,152.0,77.0,48.0,...,4.3,73.0,0.4,24.0,22.0,31.0,7.3,10.3,1.40,110.0
1,00006825,155.0,63.0,72.0,25.17,9.1,2.58,177.0,113.0,48.0,...,3.5,130.0,0.5,30.0,34.0,26.0,6.1,10.7,0.99,203.0
2,00010603,117.0,71.0,95.0,35.47,5.5,2.14,195.0,150.0,60.0,...,2.9,54.0,0.3,28.0,13.0,8.0,6.0,8.7,0.51,91.0
3,00013474,130.0,63.0,78.0,31.46,5.2,2.88,190.0,104.0,67.0,...,4.9,86.0,0.5,26.0,19.0,18.0,7.5,9.6,0.63,90.0
4,00018895,169.0,61.0,58.0,18.36,5.4,2.66,190.0,96.0,82.0,...,4.0,71.0,1.1,36.0,34.0,14.0,6.6,9.3,0.50,97.0

### Urinalysis

In [64]:
# PH
ph_1a = get_unique_data(3015501, 'ph_1a', keep_date = True, data_col_name = 'measurement_datetime_1a')
ph_1b = get_unique_data(3015736, 'ph_1b', keep_date = True, data_col_name = 'measurement_datetime_1b')
ph_1 = combine_cols(ph_1a, ph_1b, 'ph_1a', 'ph_1b', 
             'measurement_datetime_1a', 'measurement_datetime_1b', 'ph_1',
             keep_date = True, date_col = 'ph_1_date')

Unique Pats: 47
Unique Pats: 4930
Unique Pats: 4958
         MRN  ph_1                 ph_1_date
0  00002048    5.0 2017-07-17 15:17:00+00:00
1  00052134    5.0 2013-02-07 09:45:00+00:00
2  00075283    5.0 2019-07-16 15:30:00+00:00
3  00080697    5.0 2017-04-15 12:46:00+00:00
4  00083451    5.0 2016-03-21 15:34:00+00:00

In [65]:
ph_2a = get_unique_data(3029305, 'ph_2a', keep_date = True, data_col_name = 'measurement_datetime_2a')
ph_2b = get_unique_data(3022621, 'ph_2b', keep_date = True, data_col_name = 'measurement_datetime_2b')
ph_2 = combine_cols(ph_2a, ph_2b, 'ph_2a', 'ph_2b', 
             'measurement_datetime_2a', 'measurement_datetime_2b', 'ph_2',
             keep_date = True, date_col = 'ph_2_date')

Unique Pats: 0
Unique Pats: 15541
Unique Pats: 15541
         MRN  ph_2                 ph_2_date
0  00002048    5.5 2025-01-28 13:00:00+00:00
1  00006825    6.5 2018-01-29 18:36:00+00:00
2  00010603    6.0 2020-01-27 10:04:00+00:00
3  00013474    5.0 2024-03-14 09:44:00+00:00
4  00018895    7.5 2013-07-19 22:15:00+00:00

In [66]:
ph = combine_cols(ph_1, ph_2, 'ph_1', 'ph_2','ph_1_date', 'ph_2_date', 'ph_urine')

Unique Pats: 15875
         MRN  ph_urine
0  00002048        5.5
1  00006825        6.5
2  00010603        6.0
3  00013474        5.0
4  00018895        7.5

In [67]:
lab_df = pd.merge(lab_df, ph, how='outer', on = 'MRN')
unique_pats = len(lab_df['MRN'].unique())
print(f'Unique Pats: {unique_pats}')
lab_df.head()

Unique Pats: 22323

,MRN,sbp,dbp,heart_rate,bmi,a1c,tsh,total_chol,ldl_chol,hdl_chol,...,alk_phos,bilirubin,aspartate_trans,alaine_trans,blood_urea_nit,protein,calcium,creatinine,glucose,ph_urine
0,00002048,148.0,71.0,74.0,26.11,6.4,3.11,152.0,77.0,48.0,...,73.0,0.4,24.0,22.0,31.0,7.3,10.3,1.40,110.0,5.5
1,00006825,155.0,63.0,72.0,25.17,9.1,2.58,177.0,113.0,48.0,...,130.0,0.5,30.0,34.0,26.0,6.1,10.7,0.99,203.0,6.5
2,00010603,117.0,71.0,95.0,35.47,5.5,2.14,195.0,150.0,60.0,...,54.0,0.3,28.0,13.0,8.0,6.0,8.7,0.51,91.0,6.0
3,00013474,130.0,63.0,78.0,31.46,5.2,2.88,190.0,104.0,67.0,...,86.0,0.5,26.0,19.0,18.0,7.5,9.6,0.63,90.0,5.0
4,00018895,169.0,61.0,58.0,18.36,5.4,2.66,190.0,96.0,82.0,...,71.0,1.1,36.0,34.0,14.0,6.6,9.3,0.50,97.0,7.5

## Save File

In [68]:
lab_df.to_csv(DATA_DIR / 'lab_raw.csv', index=False)